#! /bin/bash -a
#
# @file			dcp-job-poster
# @description		Checks if there are currently jobs in the queue on the board.
#			If less then X jobs are available then post Y more jobs to the board.
# @author		Matthew Palma, mpalma@sparc.network
# @date			April 2018
#

dcp_root=/home/ec2-user/DCP/dcp-cli
dcp_db=/home/ec2-user/DCP/DCP-Core/db/board
output="$dcp_root/utils/log"
stderr="$dcp_root/utils/err"
node=/home/ec2-user/.nvm/versions/node/v9.11.1/bin/node

dcp_job="$dcp_root/dcpjob"
job_opt="deploy ./examples/narcnum/job.json"

min_jobs=5
num_post=5

cd "$dcp_root"

num_jobs=$(ls "$dcp_db/jobs/static/open/" -1 | wc -l)
if [ "$num_jobs" -le "$min_jobs" ]; then
  for ((i=0; i<num_post; i++)) do
    echo "need to post jobs!"
    $node $dcp_job $job_opt &>> $output
  done
else
  echo "No need to post jobs"
fi
