# @file         mkdocs.yml
# @author       Brandon Christie <brandon@distributive.network>
# @date         Mar 2023
#
# @description  Determines how the component of name: 'dcp-util'
#               is formatted on backstage.

site_name: dcp-util
repo_url: https://gitlab.com/Distributed-Compute-Protocol/dcp-util
edit_uri: edit/main/docs
docs_dir: .
nav:
  - README.md
plugins:
  - techdocs-core
  - same-dir
